### ISSUE TITLE
javascript.horse JSON

### ISSUE THREAD

**Issue by Daniel15** [bnjbvr/horsejsbot#1]
http://javascript.horse/random.json
So you don't have to parse HTML

Have fun :stuck_out_tongue:

**Comment by bnjbvr** [comment]
Thanks for the endpoint! :)
Fixed in f6021d002e4d9680df5984f7204ed256c8ec75d3

**Comment by bnjbvr** [comment]
@Daniel15, any chance you were involved with hosting javascript.horse? It seems the site is encountering some PHP error, and I don't know who's in charge of hosting this website.

**Comment by Daniel15** [comment]
Oops, sorry about that @bnjbvr! I fixed it now. I recently switched from HHVM back to PHP because I started encountering a few issues with HHVM, and forgot I didn't have SQLite installed in PHP (as I don't have any other sites that use it).

**Comment by bnjbvr** [comment]
Thank you @Daniel15 :-)
